disabled_rules:
  - identifier_name
  - conditional_returns_on_newline
  - discouraged_optional_collection
  - file_header
  - strict_fileprivate
  - switch_case_on_newline
  - type_body_length
  - opening_brace
  - large_tuple
  - todo

included:
  - Sources/SwiftNES
  - Sources/SwiftNESMain
  - Tests/SwiftNESTests

file_length:
  warning: 300
  error: 600

function_body_length:
  warning: 100
  error: 200

trailing_comma:
    mandatory_comma: true

line_length:
    ignores_comments: true
