disabled_rules:
- identifier_name
- conditional_returns_on_newline
- discouraged_optional_collection
- file_header
- strict_fileprivate
- switch_case_on_newline

included:
- Sources/SwiftNES
- Tests/SwiftNESTests

file_length:
- 120
- 200

function_body_length:
- 100
- 200

