name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install sdl2 gd swiftlint libsoundio
    - name: Lint
      run: make lint
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

